name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Install Raku
        uses: Raku/setup-raku@v1
        with:
          raku-version: 'latest'

      - name: Raku version
        run: raku --version

      - name: Install BDD::Behave
        run: zef install --/test --force-install https://github.com/gdonald/BDD-Behave.git

      - name: Install Template::HAML
        run: zef install --/test --force-install https://github.com/gdonald/Template-HAML.git

      - name: Install dependencies
        run: zef install --/test --test-depends --deps-only .

      - name: Run behave specs
        run: raku test.raku
